version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_USER: jezreel
      MYSQL_DATABASE: comateq002
      MYSQL_PASSWORD: test1234
    ports:
      - 3306:3306